# Generated by Django 4.2.5 on 2023-09-23 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.TextField()),
                ('apellido', models.TextField()),
                ('fechaCreacion', models.DateField(auto_now_add=True, db_column='fecha_creacion')),
                ('fechaActualizacion', models.DateTimeField(auto_now=True, db_column='fecha_actualizacion')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('direccion', models.TextField()),
                ('tipo', models.TextField(choices=[('BODEGA', 'BODEGA'), ('MERCADO', 'MERCADO')])),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('fechaActualizacion', models.DateTimeField(auto_now=True, db_column='fecha_actualizacion')),
            ],
            options={
                'db_table': 'tiendas',
            },
        ),
        migrations.CreateModel(
            name='Relevo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(null=True, upload_to='imagenes_relevos/')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('implementado', models.TextField(choices=[('MERCADERISMO', 'MERCADERISMO'), ('SIN MERCADERISMO', 'SIN MERCADERISMO')])),
                ('estado', models.TextField(choices=[('EFECTIVO', 'EFECTIVO'), ('NO DESEA', 'NO DESEA'), ('CERRADO', 'CERRADO')])),
                ('tienda', models.ForeignKey(db_column='tienda_id', on_delete=django.db.models.deletion.PROTECT, to='proyecto.tienda')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'relevos',
            },
        ),
    ]
